// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsk81pXDoQDxMgyB9JF4jX3-86k5qutVc',
    appId: '1:466420454306:web:8aa25e1f621b9f1433d8fb',
    messagingSenderId: '466420454306',
    projectId: 'virtuwatch-711e4',
    authDomain: 'virtuwatch-711e4.firebaseapp.com',
    storageBucket: 'virtuwatch-711e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfJ7T6ZuVG20iD8E4OV2P9jG9GQlSdjdo',
    appId: '1:466420454306:android:5071bdab880703ca33d8fb',
    messagingSenderId: '466420454306',
    projectId: 'virtuwatch-711e4',
    storageBucket: 'virtuwatch-711e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFW_Ru5gXGF5i0FbNnURc1YgCh5i_S_zs',
    appId: '1:466420454306:ios:4dfe70246334024233d8fb',
    messagingSenderId: '466420454306',
    projectId: 'virtuwatch-711e4',
    storageBucket: 'virtuwatch-711e4.firebasestorage.app',
    iosBundleId: 'com.urbanetime.virtuwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFW_Ru5gXGF5i0FbNnURc1YgCh5i_S_zs',
    appId: '1:466420454306:ios:4dfe70246334024233d8fb',
    messagingSenderId: '466420454306',
    projectId: 'virtuwatch-711e4',
    storageBucket: 'virtuwatch-711e4.firebasestorage.app',
    iosBundleId: 'com.urbanetime.virtuwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsk81pXDoQDxMgyB9JF4jX3-86k5qutVc',
    appId: '1:466420454306:web:bcc93685a794786833d8fb',
    messagingSenderId: '466420454306',
    projectId: 'virtuwatch-711e4',
    authDomain: 'virtuwatch-711e4.firebaseapp.com',
    storageBucket: 'virtuwatch-711e4.firebasestorage.app',
  );
}
